name = "tiktok-downloader"

[build]
command = "npm run build"
[build.environment]
NODE_VERSION = "18"

[site]
bucket = ".next"

[env.production]
pages_build_output_dir = ".next"
vars = { ENVIRONMENT = "production" }

[env.staging]
pages_build_output_dir = ".next"
vars = { ENVIRONMENT = "staging" }

[env.development]
pages_build_output_dir = ".next"
vars = { ENVIRONMENT = "development" }

