name = "tiktok-downloader"

[build]
command = "npm run build"
[build.environment]
NODE_VERSION = "18"

[site]
bucket = ".next"

[pages]
  [pages.environment]
    production = { pages_build_output_dir = ".next", vars = { ENVIRONMENT = "production" } }
    staging = { pages_build_output_dir = ".next", vars = { ENVIRONMENT = "staging" } }
    development = { pages_build_output_dir = ".next", vars = { ENVIRONMENT = "development" } }
